=== bcordeirodev/acerbrag/Optimuz/config/dtd/local-settings.dtd
<?xml version='1.0' encoding='UTF-8'?><!--- Main settings element. -->

<!ELEMENT settings (page,app,report,errors,log,performance,resources,session,format,htmlElements,orm,smtp,systemAccess,threading)>


<!ELEMENT app (photos,albums,videos,banners,liveServer)*>
<!ATTLIST app
    name CDATA #REQUIRED
    version CDATA #REQUIRED
    enable (true|false) #REQUIRED
  >
<!ELEMENT photos EMPTY>
<!ATTLIST photos
    savePath CDATA #REQUIRED
  >
<!ELEMENT albums EMPTY>
<!ATTLIST albums
    savePath CDATA #REQUIRED
  >
<!ELEMENT videos EMPTY>
<!ATTLIST videos
    thumbPath CDATA #REQUIRED
  >
<!ELEMENT banners EMPTY>
<!ATTLIST banners
    savePath CDATA #REQUIRED
  >
<!ELEMENT liveServer EMPTY>
<!ATTLIST liveServer
    url CDATA #IMPLIED
  >


<!ELEMENT page (description,keywords,charset,language,title,doctype,markup)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT keywords (#PCDATA)>
<!ELEMENT charset (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT doctype (#PCDATA)>
<!ELEMENT markup (#PCDATA)>


<!ELEMENT report (email)+>
<!ATTLIST report
    enable (true|false) #REQUIRED
  >
<!ELEMENT email EMPTY>
<!ATTLIST email
    name CDATA #REQUIRED
    value CDATA #REQUIRED
  >


<!ELEMENT errors (defaultControllerHandler)*>
<!ELEMENT defaultControllerHandler (#PCDATA)>


<!ELEMENT log (format)*>
<!ATTLIST log
    enable (true|false) #REQUIRED
  >
<!ELEMENT format (currency)*>
<!ATTLIST format
    type (short|complete) #IMPLIED
  >


<!ELEMENT performance (cache,minify,compress,mergeFiles)*>
<!ELEMENT cache EMPTY>
<!ATTLIST cache
    enable (true|false) #REQUIRED
  >
<!ELEMENT minify EMPTY>
<!ATTLIST minify
    enable (true|false) #REQUIRED
  >
<!ELEMENT compress EMPTY>
<!ATTLIST compress
    enable (true|false) #REQUIRED
    method (gzip|deflate) #REQUIRED
    level (0|1|2|3|4|5|6|7|8|9) #REQUIRED
  >
<!ELEMENT mergeFiles EMPTY>
<!ATTLIST mergeFiles
    enable (true|false) #REQUIRED
  >


<!ELEMENT resources (storage,controller)*>
<!ELEMENT storage EMPTY>
<!ATTLIST storage
    engine (files|session) #IMPLIED
    lifetime CDATA #IMPLIED
  >
<!ELEMENT controller (#PCDATA)>


<!ELEMENT session (autoStart,savePath,timeout,cookie,saveState,autoLoadSavedState)*>
<!ELEMENT autoStart EMPTY>
<!ATTLIST autoStart
    enable (true|false) #REQUIRED
  >
<!ELEMENT savePath EMPTY>
<!ATTLIST savePath
    value CDATA #REQUIRED
  >
<!ELEMENT timeout (#PCDATA)>
<!ATTLIST timeout
    time CDATA #IMPLIED
    autoUpdate (true|false) #IMPLIED
  >
<!ELEMENT cookie (name,encrypt)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT encrypt (#PCDATA)>


<!ELEMENT currency (#PCDATA)>


<!ELEMENT smtp (host,user,pwd,timeout)*>
<!ATTLIST smtp
    enable (true|false) #REQUIRED
  >
<!ELEMENT host (local,remote)*>
<!ELEMENT local (name)*>
<!ELEMENT remote (name,port,security)*>
<!ELEMENT port (#PCDATA)>
<!ELEMENT security (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT pwd (#PCDATA)>


<!ELEMENT systemAccess (database,customValidator)*>
<!ATTLIST systemAccess
    enable (true|false) #REQUIRED
    handler (files|database) #REQUIRED
  >
<!ELEMENT database (role,permission)*>
<!ELEMENT role EMPTY>
<!ATTLIST role
    tableName CDATA #REQUIRED
    primaryKey CDATA #REQUIRED
    labelName CDATA #REQUIRED
  >
<!ELEMENT permission EMPTY>
<!ATTLIST permission
    tableName CDATA #REQUIRED
    primaryKey CDATA #REQUIRED
    labelName CDATA #REQUIRED
  >
<!ELEMENT customValidator (#PCDATA)>


<!ELEMENT threading (log,limit)*>
<!ELEMENT limit EMPTY>
<!ATTLIST limit
    value CDATA #REQUIRED
  >


<!ELEMENT htmlElements (session)*>
<!ELEMENT saveState EMPTY>
<!ATTLIST saveState
    enable (true|false) #REQUIRED
  >
<!ELEMENT autoLoadSavedState EMPTY>
<!ATTLIST autoLoadSavedState
    enable (true|false) #REQUIRED
  >


<!ELEMENT orm (propel,notorm)*>
<!ELEMENT propel EMPTY>
<!ATTLIST propel
    enable (true|false) #REQUIRED
  >
<!ELEMENT notorm (connection)*>
<!ATTLIST notorm
    enable (true|false) #REQUIRED
  >
<!ELEMENT connection EMPTY>
<!ATTLIST connection
    dsn CDATA #REQUIRED
    user CDATA #REQUIRED
    password CDATA #REQUIRED
  >

=== bcordeirodev/acerbrag/Optimuz/apps/default/config/settings/local.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/local-settings.dtd">
<!--
This is the main configuration file of the application. All values defined here
can be changed in runtime through the Configuration class, but these changes are
valid ONLY during the script runtime. Settings not defined here also can be
defined in runtime, and will be valid during the script runtime.

Note that when we refer to CLIENT in this file, we are refering to the UA (User
Agent) that made the HTTP request.

Settings defined here are used in many places of the application, so take care
to not make mistakes.
-->
<settings>
	<!--
	[Local only]
	Settings related to the application.

	- title: applicaion's title. This title is used as the default title for all
	application's pages.

	- version:  application's version.

	- enable: if this parameter is true the application will be accessable for
	all users. Otherwise, the access to this application will be denied.
	-->
	<app name="Votorantim" version="0.1" enable="true">
		<!--
		[Local only]
		Path to save uploaded images of articles. Should follow the pattern
		APPLICATION_NAME/path/to/save. The wildcard "~" must NOT be used.

		This path is relative to the resource folder and follow the same rules of
		any other resource.
		-->
		<photos savePath="default/imgs/" />

		<!--
		[Local only]
		Path to save uploaded images of albums. Should follow the pattern
		APPLICATION_NAME/path/to/save. The wildcard "~" must NOT be used.

		This path is relative to the resource folder and follow the same rules of
		any other resource.
		-->
		<albums savePath="default/imgs/" />

		<!--
		[Local only]
		Path to save the thumbnails of videos. Should follow the pattern
		APPLICATION_NAME/path/to/save. The wildcard "~" must NOT be used.

		This path is relative to the resource folder and follow the same rules of
		any other resource.
		-->
		<videos thumbPath="default/imgs/" />

		<!--
		[Local only]
		This settings are related to the banners published on the site.
		-->
		<banners savePath="default/imgs/" />

		<!--
		[Local only]
		Path to save the thumbnails of videos. Should follow the pattern
		APPLICATION_NAME/path/to/save. The wildcard "~" must NOT be used.

		This path is relative to the resource folder and follow the same rules of
		any other resource.
		-->
		<liveServer url="" />
	</app>

	<!--
	[Global and local]
	Default settings applied in all pages of the application. These settings
	can be changed in runtime to be applied individualy.
	-->
	<page>
		<description></description>
		<keywords></keywords>
		<charset>UTF-8</charset>
		<language>pt-br</language>
		<title>Votorantim</title>
		<doctype>strict</doctype>
		<markup>html</markup>
	</page>

	<!--
	[Global and local]
	E-mail's addresses used to send report, warning and error messages from the
	application.
	-->
	<report enable="false">
		<error value="suporte@legalway.com.br" />
		<webmaster value="log@legalway.com.br" />
		<report value="log@legalway.com.br" />
		<noreply value="suporte@legalway.com.br" />
		<support value="log@legalway.com.br" />
		<system value="suporte@legalway.com.br" />
	</report>

	<!--
	[Global and local]
	Settings about error handling.
	-->
	<errors>
		<!--
		This setting sets a page controller used to handle errors catched by the
		method Error::handleError().

		If you provide a controller here, this controller must be a page
		controller and extends the DefaultPageController or DefaultController
		class. But if you don't provide a controller, the Error class will
		call the static error page to give the user a feedback about the error.

		The controller must have a constructor to receive the following
		parameters (in this order): $errorNumber, $errorMessage, $errorFile,
		$errorLine. An example of a valid constructor signature is:

		public function __construct($errorNumber = null, $errorMessage = null, $errorFile = null, $errorLine = null)
		-->
		<defaultControllerHandler></defaultControllerHandler>
	</errors>

	<!--
	[Global and local]
	Log settings.
	-->
	<log enable="true">
		<!--
		The tag "format" sets the log messages format, and can have the
		following values:
		- short: will store only the event date/time, the message and its level.
		- complete: will store, besides the basic information, other
		informations like IP, Browser, stacktrace, etc.
		-->
		<format type="complete" />
	</log>

	<!--
	[Global and local]
	These settings are related to performance and need more atention. They are:

	- cache: enable/disable the use of cache in the application. This is not
	related to the cache on client, but only the application cache. This cache
	are files stored in the directory /Optimuz/cache/. To handle this cache you
	can use the Cache class located in the Core package.

	- minify: enable/disable the process of minifying resource files (CSS and
	Javascript). This affects only the files included with the
	ResourceController class.

	- compress: enable/disable the process of compressing files sent to the
	client. These files includes resource files (CSS and Javascript), the
	HTML content or any other content that can be sent with the
	HttpScriptResponse class. NOTE: the compression is not done in the
	HttpScriptResponse class, usualy it is done in the DefaultView class. So if
	you want to compress any content that will not be sent by a view, do it
	manualy before send. The compression can be done using one of two methods:
	gzip (default) or deflate.

	- mergeFiles: enable/disable the concatenation of resource files (CSS and
	Javascript) sent to the client. If this option is turned on, all CSS files
	for example, will be sent as one file in one request.
	-->
	<performance>
		<cache enable="false" />
		<minify enable="true" />
		<compress enable="false" method="gzip" level="5" />
		<mergeFiles enable="false" />
	</performance>

	<!--
	[Local only]
	Default settings about the engine used to store resource files. These
	settings are used by the Resource package.
	-->
	<resources>
		<!--
		The "storage" element can have the following attributes:

		- engine: the value can be "files" (default) or "session".

		- lifetime: the lifetime (in seconds) of a resource file when it is
		cached. After this time, the resource must be renewed in the client
		cache. This is only used when the resource file is cached in the client
		cache.
		-->
		<storage engine="files" lifetime="3600" />

		<!--
		URL of a public controller used to handle resources requests. The
		controller must be located in the controller's public package
		(/Optimuz/apps/APPLICATION_NAME/layers/control/page).

		Example of a valid value for this setting is "/resource" (without
		quotes). In this case there must be a controller named
		ResourceController in the path
		/Optimuz/apps/APPLICATION_NAME/layers/control/page, so complete path is
		/Optimuz/apps/APPLICATION_NAME/layers/control/page/ResourceController.php.

		If no controller is specified, than resource files will be loaded
		directly from the resources directory
		(/Optimuz/apps/APPLICATION_NAME/layers/view/resource).
		-->
		<controller></controller>
	</resources>

	<!--
	[Global and local]
	Session settings used by the application.
	-->
	<session>
		<!--
		Enable/disable the session auto start in the first time the user visit
		the application.
		-->
		<autoStart enable="true" />

		<!--
		Session's save path. This path is relative to the application directory
		(/Optimuz/apps/APPLICATION_NAME/). So if the value of this setting is
		"some/folder/" and the current application is "default", the session
		files will be saved on "/Optimuz/apps/default/some/folder/". If this
		setting is empty, the global session's path will be used
		(/Optimuz/session/).
		-->
		<savePath value="session/" />

		<!--
		Settings related to the session lifetime.

		The attribute 'value' sets the default session expiration time in
		minutes. If its value is 0 (zero) then the validation to check whether
		the session is still valid will be disabled. In other words, the session
		is meant to be "always valid", though it can still be closed if the PHP
		GC finds that the session file is too older.

		The attribute 'autoUpdate' sets whether the session timeout must to be
		updated automatically on each request. If it is set to true, on every
		request the session start time will be set to the current time,
		extending the session lifetime. If it is set to false, the session start
		time will not be updated and the session itself will be closed after the
		timeout specified by the attribute 'value'. Default for this attribute
		is true.
		-->
		<timeout time="120" autoUpdate="true" />

		<!--
		Settings related to the session's cookie.
		-->
		<cookie>
			<!--
			Custom name used for the session cookie.

			If this setting is empty, then the default name will be used. The
			default name for the session cookie is the application's name.

			If the application is not using its own session (i.e., the savePath
			setting above is not set) the cookie name will be the PHP default.
			-->
			<name></name>

			<!--
			If the encrypt parameter is set, then the name will be encrypted using
			the class Serial from the Core package. The encrypted name will have
			two blocks of five digits.
			-->
			<encrypt>false</encrypt>
		</cookie>
	</session>

	<!--
	[Global and local]
	Default formats.
	-->
	<format>
		<currency>R$</currency>
	</format>

	<!--
	[Global and local]
	SMTP settings.
	-->
	<smtp enable="true">
		<host>
			<!--
			Settings about the local host. The local host is the one where the
			application is running.
			-->
			<local>
				<name>localhost</name>
			</local>

			<!--
			Settings about the host where the SMTP server is running.
			-->
			<remote>
				<name>mail.legalway.com.br</name>
				<port>25</port>
				<security></security>
			</remote>
		</host>
		<!--
		Settings related to SMTP authentication.
		-->
