=== bcordeirodev/acerbrag/Optimuz/config/dtd/site-navigation.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT navigation (link)*>
<!ATTLIST navigation
    includeAppBaseUrl (true|false) #IMPLIED
  >
<!ELEMENT link (link)*>
<!ATTLIST link
    label CDATA #REQUIRED
    title CDATA #IMPLIED
    url CDATA #REQUIRED
    mainMenu (true|false) #IMPLIED
    isHome (true|false) #IMPLIED
    includeHome (true|false) #IMPLIED
    systemAccessController CDATA #IMPLIED
    systemAccessPermissions CDATA #IMPLIED
  >

=== bcordeirodev/acerbrag/Optimuz/apps/default/config/settings/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/site-navigation.dtd">
<!--
Configuration file of the application navigation. This file is primarily used by
the SiteNavigationComponent and MenuComponent.

Each link element is mapped to a controller. Below is a sample:

<link label="link text" title="link title" url="URL part" mainMenu="boolean" isHome="boolean" includeHome="boolean" systemAccessController="controller/method name" systemAccessPermissions="required permissions list">
	<link label="link text" title="link title" url="URL part" mainMenu="boolean" systemAccessController="controller/method name"></link>
</link>

And now a sample of a (X)HTML link generated by the SiteNavigation class:

<a href="url" title="title">label</a>

Below is an explanation of all attributes:

- label: This is the text displayed in the link.

- title: The title of a link.

- url: This is the URL version of a class name or method name of the mapped
controller. So if you are mapping the call PageController::SomeMethod(), the url
attribute should be just "page" (for the controller) or "some-method" (for the
method). Any URL that does not match to an existing controller/method will be
ignored by the SiteNavigation class, but still can be used by the MenuController
if the mainMenu attribute is set to true.

- mainMenu: This attribute specifies whether the link should be displayed in the
main menu of the application. This menu is built using the MenuComponent. This
attribute accept the values true or false. Default is false.

- isHome: Sets the link as the home page. This is the initial link, from where
the site navigation begins. It accepts a boolean value and only one link can be
set as home (isHome="true"). Default is false.

- includeHome: Sets whether the path of the home link must to be included into
other links. If this is set to true, then all rendered links of the site
navigation will begin with the home link. Only the home link uses this property.
If this property is not set, the SiteNavigationComponent assumes it as false.
See the following example to understand:

	includeHome = true
	/home			>>> home link
	/home/other		>>> other link

	includeHome = false
	/home			>>> home link
	/other			>>> other link

- systemAccessController: Sets the controller associated with the link. The
controller's access right is defined in the systemAccess/map.xml file.

- systemAccessPermissions: Sets the required permissions for the link. These
permissions can be set as a comma separated list or a single permission. It's a
good practice to be in the slug form as "permission-name".

- includeAppBaseUrl: Whether to include the application's base URL into the
item's URL. If is true the generated link will look something like /app/link,
otherwise it will look like /link.
-->
<navigation includeAppBaseUrl="true" >
	<link label="Dashboard" title="" url="~/dashboard" mainMenu="true" isHome="true" includeHome="false" icon="mdi mdi-chart-bar"></link>
	<link label="Usuarios" title="Gerenciar usuários" url="javascript:;" mainMenu="true" icon="mdi mdi-account" systemAccessController="Usuario" systemAccessPermissions="gerenciar-usuarios">
		<link label="Ver todos" title="Gerenciar usuários" url="~/usuario" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Nuevo" title="Permite o cadastro de um novo usuário" url="~/usuario/nuevo" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Ativos" title="Lista apenas os usuários ativos no sistema" url="~/usuario/ativos" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Inativos" title="Lista apenas os usuários inativos no sistema" url="~/usuario/inativos" mainMenu="true" systemAccessPermissions="*"></link>
	</link>
	<link label="Prêmios" title="" url="javascript:;" mainMenu="true" icon="mdi mdi-gift" systemAccessController="Premio">
		<link label="Ver todos" title="" url="~/premio" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Nuevo" title="" url="~/premio/nova" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Ativos" title="" url="~/premio/ativas" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Inativos" title="" url="~/premio/inativas" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Solicitações de Regaste" title="" url="~/premio/solicitacoes" mainMenu="true" systemAccessPermissions="*"></link>
	</link>
	<link label="Notícias" title="Gerenciar agenda" url="javascript:;" mainMenu="true" icon="mdi mdi-newspaper" systemAccessController="Noticia">
		<link label="Ver todas" title="Todos as noticias" url="~/noticia" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Nova" title="Permite o cadastro de um nova noticia" url="~/noticia/nova" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Ativas" title="Lista apenas as noticias ativas no sistema" url="~/noticia/ativas" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Inativas" title="Lista apenas as noticias inativas no sistema" url="~/noticia/inativas" mainMenu="true" systemAccessPermissions="*"></link>
	</link>
	<link label="Encuestas" title="Gerenciar pesquisas" mainMenu="true" url="javascript:;" icon="mdi mdi-magnify" systemAccessController="Pesquisa">
		<link label="Ver todas" title="Ver todas as pesquisas" url="~/pesquisa" systemAccessPermissions="visualizar-pesquisa" mainMenu="true"></link>
		<link label="Nueva" title="Nova pesquisa" url="~/pesquisa/nova" mainMenu="true" systemAccessPermissions="cadastrar-pesquisa"></link>
	</link>
	<link label="Colecciones" title="" url="~/coleta" mainMenu="true" includeHome="false" icon="mdi mdi-file-document" systemAccessController="Coleta"></link>
	<link label="Informes" title="" url="javascript:;" mainMenu="true" includeHome="false" icon="mdi mdi-chart-bar" systemAccessController="Relatorio">
		<link label="Analítico" title="Ver relatorio analitico" url="~/relatorio/analitico" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Por usuário" title="Ver relatório por usuário" url="~/relatorio/usuario" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Por aplicação" title="Ver relatório por aplicação" url="~/relatorio/aplicacao" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Descriptivo" title="Ver relatório descritivo" url="~/relatorio/descritivo" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Perfíl amostral" title="Ver relatório descritivo" url="~/relatorio/perfil-amostral" mainMenu="true" systemAccessPermissions="*"></link>
		<link label="Geral" title="Ver relatório descritivo" url="~/relatorio/geral" mainMenu="true" systemAccessPermissions="*"></link>
	</link>
	<link label="Registro de base" url="javascript:;" mainMenu="true" systemAccessController="CadastroBasico" icon="fa fa-puzzle-piece">
		<link label="Perfiles" url="~/cadastro-basico/perfiles" mainMenu="true" systemAccessPermissions="gerenciar-perfis"></link>
		<link label="Cargos" url="~/cadastro-basico/cargos" mainMenu="true" systemAccessPermissions="gerenciar-cargos"></link>
		<link label="Departamentos" url="~/cadastro-basico/departamentos" mainMenu="true" systemAccessPermissions="gerenciar-departamentos"></link>
	</link>
</navigation>
