=== bcordeirodev/acerbrag/Optimuz/config/dtd/validation.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT form (custom-rules*,input+)>
<!ATTLIST form
    method (get|post) #REQUIRED
    lang CDATA #IMPLIED
  >
<!ELEMENT custom-rules (rule)+>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
    name (required|alpha|text|number|bool|array|email|url|date|password|comparePasswords|compareRequireds|compareDates|length|match|cnpj|cpf|upload|discard) #REQUIRED
    regex CDATA #IMPLIED
    errorMessage CDATA #IMPLIED
    accept CDATA #IMPLIED
    allowSequences (true|false) #IMPLIED
    sequencesMaxLength CDATA #IMPLIED
    min CDATA #IMPLIED
    max CDATA #IMPLIED
    fixed CDATA #IMPLIED
    types CDATA #IMPLIED
    size CDATA #IMPLIED
    items CDATA #IMPLIED
    second CDATA #IMPLIED
    requiredValue CDATA #IMPLIED
    differentValue CDATA #IMPLIED
    required (true|false) #IMPLIED
    strict (true|false) #IMPLIED
  >
<!ELEMENT input (rule)+>
<!ATTLIST input
    name CDATA #REQUIRED
    label CDATA #IMPLIED
	hasHTML (true|false) #IMPLIED
    isUrlEncoded (true|false) #IMPLIED
  >

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Noticia/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="titulo" label="Título">
		<rule name="required" />
	</input>
	<input name="sub-titulo" label="Sub título">
		<rule name="required" />
	</input>
	<input name="descricao" label="Descrição">
		<rule name="required" />
	</input>
	<input name="igrejas" label="Lugar a apresentar">
		<rule name="array" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Podcast/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4}-\d{4,5}/" errorMessage="O formato do telefone deve ser 00 00000-0000" />

		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
		<rule name="long" regex="/^-?\d+(\.\d+)?$/" errorMessage="A longitude não foi informada corretamente" />
		<rule name="lat" regex="/^-?\d+(\.\d+)?$/" errorMessage="A latitude não foi informada corretamente" />
	</custom-rules>

	<input name="titulo" label="Nome fantasia">
		<rule name="required" />
	</input>
	<input name="descricao" label="Razão social">
		<rule name="required" />
	</input>
	<input name="igrejas" label="Lugar a apresentar">
		<rule name="array" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/PedidoOracao/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="id" label="Id do podcast">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="descricao-atendimento" label="Descrição de atendimetno">
		<rule name="discard" />
	</input>
	<input name="atendido" label="Atendido">
		<rule name="required" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pesquisa/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="pesquisa-id" label="">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="titulo" label="Título">
		<rule name="discard" />
	</input>
	<input name="data-inicio" label="Data de início">
		<rule name="date" />
		<rule name="compareDates" second="data-fim" />
	</input>
	<input name="data-fim" label="Data de término">
		<rule name="date" />
	</input>
	<input name="descricao" label="Descrição da Pesquisa">
		<rule name="discard" />
	</input>
	<input name="status" label="Descrição da Pesquisa">
		<rule name="discard" />
	</input>
	<input name="quantidade-pontos" label="Quantidade de pontos">
		<rule name="required" />
	</input>
	<input name="tipo-pesquisa" label="Tipo de pesquisa">
		<rule name="required" />
	</input>
	<input name="pesquisa-anonima" label="Pesquisa anonima">
		<rule name="required" />
	</input>

	<input name="sexo" label="Sexo">
		<rule name="discard" />
	</input>
	<input name="idade-minima" label="Idade Mínima">
		<rule name="discard" />
	</input>
	<input name="idade-maxima" label="Idade Máxima">
		<rule name="discard" />
	</input>

	<input name="id-categorias">
		<rule name="array"/>
	</input>
	<input name="categorias">
		<rule name="array"/>
	</input>
	<input name="id-perguntas">
		<rule name="array"/>
	</input>
	<input name="perguntas">
		<rule name="array"/>
	</input>
	<input name="alternativas">
		<rule name="array"/>
	</input>
	<input name="id-alternativas">
		<rule name="array"/>
	</input>
	<input name="tipo-resposta">
		<rule name="array"/>
	</input>
	<input name="novas-alternativas">
		<rule name="array"/>
	</input>
	<input name="novas-alternativas-img">
		<rule name="array"/>
	</input>
	<input name="options-removed">
		<rule name="array"/>
	</input>
	<input name="questions-removed">
		<rule name="array"/>
	</input>

	<input name="text-question" label="">
		<rule name="array" />
	</input>
	<input name="type-response" label="">
		<rule name="array" />
	</input>
	<input name="category" label="">
		<rule name="array" />
	</input>
	<input name="options" label="">
		<rule name="array" />
	</input>
	<input name="required" label="">
		<rule name="array" />
	</input>
	<input name="exception" label="">
		<rule name="discard" />
	</input>
	<input name="trigger" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/CadastrarUsuario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4,5}-\d{4}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cpf" regex="/\d{3}.\d{3}.\d{3}-\d{2}/" errorMessage="O formato do cpf deve ser 000.000.000-00" />
	</custom-rules>

	<input name="nome-completo" label="Nome completo">
		<rule name="required" />
		<rule name="letters" />
	</input>
	<input name="email" label="E-mail">
		<rule name="required" />
		<rule name="email" />
	</input>
	<input name="rg" label="RG">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="cpf" label="CPF">
		<rule name="required" />
		<rule name="cpf" />
	</input>
	<input name="celular" label="Celular">
		<rule name="required" />
		<rule name="phone" />
	</input>
	<input name="cadastro-senha" label="Senha">
		<rule name="required" />
		<rule name="password" accept="letters,numbers,symbols" allowSequences="false" sequencesMaxLength="4" />
		<rule name="length" min="8" />
	</input>
	<input name="confirmar-cadastro-senha" label="Confirmar E-mail">
		<rule name="required" />
		<rule name="password" accept="letters,numbers,symbols" allowSequences="false" sequencesMaxLength="4" />
		<rule name="comparePasswords" second="cadastro-senha" errorMessage="Confirmar cadastro senha"/>
	</input>
	<input name="tipo-cliente" label="Tipo de cliente">
		<rule name="number"/>
		<rule name="required"/>
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Membro/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4}-\d{4,5}/" errorMessage="O formato do telefone deve ser 00 00000-0000" />
		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
		<rule name="cpf-rule" regex="/\d{3}.\d{3}.\d{3}-\d{2}/" errorMessage="O formato do cpf deve ser 000.000.000-00" />
	</custom-rules>

	<input name="nome-completo" label="Nome completo">
		<rule name="discard" />
	</input>
	<input name="rg" label="RG">
		<rule name="discard" />
	</input>
	<input name="cpf" label="CPF">
		<rule name="cpf-rule" />
		<rule name="cpf" />
		<rule name="discard" />
	</input>
	<input name="rg" label="RG">
		<rule name="discard" />
	</input>
	<input name="sexo" label="Sexo">
		<rule name="discard" />
	</input>
	<input name="usuario" label="Usuário">
		<rule name="discard" />
		<rule name="number" />
	</input>
	<input name="email" label="E-mail">
		<rule name="discard" />
	</input>
	<input name="telefone-residencial" label="Telefone residêncial">
		<rule name="discard" />
		<rule name="phone" />
	</input>
	<input name="telefone-celular" label="Telefone celular">
		<rule name="discard" />
		<rule name="phone" />
	</input>
	<input name="profissao" label="profissao">
		<rule name="discard" />
	</input>

	<input name="cidade-naturalidade" label="Cidade de nascimento">
		<rule name="discard" />
	</input>
	<input name="data-nascimento" label="Data de nascimetno">
		<rule name="discard" />
	</input>

	<input name="batizado" label="Batizado">
		<rule name="discard" />
	</input>
	<input name="data-membro" label="Data membro">
		<rule name="discard" />
	</input>
	<input name="filial" label="Filial">
		<rule name="discard" />
	</input>
	<input name="cristao" label="Cristão">
		<rule name="discard" />
	</input>
	<input name="nome-cargo" label="Cargo">
		<rule name="discard" />
	</input>

	<input name="participa-pg" label="Participa de PG">
		<rule name="discard" />
	</input>
	<input name="nome-pg" label="Nome da PG">
		<rule name="discard" />
	</input>

	<input name="nome-igreja-origem" label="Igreja de origem">
		<rule name="discard" />
	</input>
	<input name="telefone-igreja-origem" label="Telefone igreja de origem">
		<rule name="discard" />
	</input>
	<input name="pastor-igreja-origem" label="Pastor igreja de origem">
		<rule name="discard" />
	</input>
	<input name="nome-antigo-ministerio" label="Nome antigo ministerio">
		<rule name="discard" />
	</input>
	<input name="experiencia" label="Experiência outra igreja">
		<rule name="discard" />
	</input>

	<input name="possui-ministerio" label="Possui ministério">
		<rule name="discard" />
	</input>
	<input name="interesse-ministerios" label="Ministérios">
		<rule name="discard" />
	</input>

	<input name="estado-civíl" label="Estado civil">
		<rule name="discard" />
	</input>
	<input name="nome-conjuge" label="Nome do conjuge">
		<rule name="discard" />
	</input>
	<input name="nome-pai" label="Nome do pai">
		<rule name="discard" />
	</input>
	<input name="nome-mae" label="Nome da mãe">
		<rule name="discard" />
	</input>

	<input name="cep" label="CEP">
		<rule name="cep" />
		<rule name="required" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard" />
		<rule name="required" />
	</input>
	<input name="numero" label="Numero">
		<rule name="number" />
		<rule name="discard" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard" />
		<rule name="required" />
	</input>
	<input name="cidade" label="Cidade">
		<rule name="number" />
		<rule name="required" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>

	<input name="nome-filho" label="Nome do filho">
		<rule name="discard" />
	</input>
	<input name="estado-civil" label="Estado civil">
		<rule name="discard" />
	</input>
	<input name="filho-cristao" label="Filho é cristão">
		<rule name="discard" />
	</input>
	<input name="nascimento-filho" label="Data de nascimento do filho">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/CadastroBasico/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>
	<input name="cadastro" label="Cadastro">
		<rule name="required" />
	</input>
	<input name="id" label="ID">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="nivel-superior" label="NÃ­vel Superior">
		<rule name="discard" />
		<rule name="number" />
	</input>	
	<input name="campos-auxiliares" label="">
		<rule name="discard" />
	</input>	
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Podcast/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="id" label="Id do podcast">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="titulo" label="Nome fantasia">
		<rule name="required" />
	</input>
	<input name="descricao" label="RazÃ£o social">
		<rule name="required" />
	</input>
	<input name="igrejas" label="Lugar a apresentar">
		<rule name="array" />
		<rule name="required" />
	</input>
	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="status" label="">
		<rule name="required" />
	</input>
</form>
