=== bcordeirodev/acerbrag/Optimuz/config/dtd/validation.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT form (custom-rules*,input+)>
<!ATTLIST form
    method (get|post) #REQUIRED
    lang CDATA #IMPLIED
  >
<!ELEMENT custom-rules (rule)+>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
    name (required|alpha|text|number|bool|array|email|url|date|password|comparePasswords|compareRequireds|compareDates|length|match|cnpj|cpf|upload|discard) #REQUIRED
    regex CDATA #IMPLIED
    errorMessage CDATA #IMPLIED
    accept CDATA #IMPLIED
    allowSequences (true|false) #IMPLIED
    sequencesMaxLength CDATA #IMPLIED
    min CDATA #IMPLIED
    max CDATA #IMPLIED
    fixed CDATA #IMPLIED
    types CDATA #IMPLIED
    size CDATA #IMPLIED
    items CDATA #IMPLIED
    second CDATA #IMPLIED
    requiredValue CDATA #IMPLIED
    differentValue CDATA #IMPLIED
    required (true|false) #IMPLIED
    strict (true|false) #IMPLIED
  >
<!ELEMENT input (rule)+>
<!ATTLIST input
    name CDATA #REQUIRED
    label CDATA #IMPLIED
	hasHTML (true|false) #IMPLIED
    isUrlEncoded (true|false) #IMPLIED
  >

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pg/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
		<rule name="long" regex="/^-?\d+(\.\d+)?$/" errorMessage="A longitude não foi informada corretamente" />
		<rule name="lat" regex="/^-?\d+(\.\d+)?$/" errorMessage="A latitude não foi informada corretamente" />
	</custom-rules>

	<input name="titulo" label="Título">
		<rule name="required" />
	</input>
	<input name="hora" label="Data">
		<rule name="required" />
	</input>
	<input name="descricao" label="Razão social">
		<rule name="required" />
	</input>
	<input name="igreja" label="Instituição ou filial">
		<rule name="required" />
	</input>

	<input name="cep" label="CEP">
		<rule name="cep" />
		<rule name="required" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard"/>
		<rule name="required" />
	</input>
	<input name="longitude" label="Longitude">
		<rule name="long" />
		<rule name="required" />
	</input>
	<input name="latitude" label="Latitude">
		<rule name="lat" />
		<rule name="required" />
	</input>
	<input name="numero" label="Número">
		<rule name="number" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard"/>
	</input>
	<input name="cidade" label="Cidade">
		<rule name="required" />
	</input>

	<input name="membro" label="Membro">
		<rule name="required" />
		<rule name="array" />
	</input>
	<input name="cargo" label="Membro">
		<rule name="array" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Ministerio/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="id" label="Id do ministério">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="nome" label="Nome do ministério">
		<rule name="required" />
	</input>
	<input name="descricao" label="Descrição do ministério">
		<rule name="required" />
	</input>
	<input name="igreja" label="Ministério ou instituição">
		<rule name="required" />
	</input>
	<input name="status" label="">
		<rule name="required" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>

	<input name="lider" label="Lider">
		<rule name="array" />
	</input>
	<input name="cargo" label="Cargo">
		<rule name="array" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Relatorio/Filtrar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="data-inicio" label="Data de inicio">
		<rule name="required" />
		<rule name="date" />
	</input>
	<input name="data-fim" label="Data final">
		<rule name="required" />
		<rule name="date" />
	</input>
	<input name="view">
		<rule name="discard"/>
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Usuario/RecuperarSenha.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="senha" label="Senha">
		<rule name="required" />
		<rule name="password" accept="letters,numbers,symbols" allowSequences="false" sequencesMaxLength="4" />
		<rule name="length" min="8" />
	</input>
	<input name="confirma-senha" label="Confirmar senha">
		<rule name="required" />
		<rule name="comparePasswords" second="senha" />
	</input>
	<input name="token-senha" label="">
		<rule name="required" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Premio/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="id" label="Id">
		<rule name="required" />
	</input>
	<input name="titulo" label="Título">
		<rule name="required" />
	</input>
	<input name="quantidade" label="Quantidade">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="valor" label="Valor">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="descricao" label="Descrição">
		<rule name="required" />
	</input>
	<input name="status" label="Status">
		<rule name="required" />
	</input>
	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Usuario/AtualizarMeuPerfil.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4}-\d{4,5}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cep-rule" regex="/\d{5}-\d{3}/" errorMessage="O formato do cep deve ser 00000-000" />
	</custom-rules>
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>
<!--	<input name="email" label="E-mail">
		<rule name="required" />
		<rule name="email" />
	</input>-->
	<input name="telefone" label="Telefone">
		<rule name="phone" />
	</input>
	<input name="permissoes" label="PermissÃµes">
		<rule name="array" />
		<!--<rule name="number" />-->
		<rule name="discard" />
	</input>

	<input name="senha" label="Senha atual">
		<rule name="discard" />
	</input>
	<input name="nova-senha" label="Nova senha">
		<rule name="password" accept="letters,numbers,symbols" allowSequences="false" sequencesMaxLength="4" />
		<rule name="length" min="8" />
	</input>
	<input name="confirma-nova-senha" label="Confirme a nova senha">
		<rule name="comparePasswords" second="nova-senha" />
		<rule name="compareRequireds" second="nova-senha" differentValue="" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pesquisa/AdicionarPergunta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="pergunta" label="Pergunta">
		<rule name="required" />
	</input>
	<input name="tipo-resposta" label="Tipo de respota">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="pesquisa-id" label="">
		<rule name="required" />
	</input>
	<input name="categoria-id" label="">
		<rule name="discard" />
	</input>
	<input name="opcoes" label="opcoes">
		<rule name="discard" />
		<rule name="Array" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pessoa/Novo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4,5}-\d{4}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
	</custom-rules>

	<input name="pessoa-id">
		<rule name="discard" />
	</input>		
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>
	<input name="cpf" label="CPF">
		<rule name="required" />
		<rule name="cpf" strict="false" />
	</input>
	<input name="email" label="E-mail">
		<rule name="email" />
	</input>
	<input name="telefone" label="Tel. residencial">
		<rule name="phone"/>
	</input>
	<input name="celular" label="Celular">
		<rule name="phone" />
		<rule name="required" />
	</input>
			
	<input name="cep" label="CEP">
		<rule name="cep" />
		<rule name="required" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard"/>
		<rule name="required" />
	</input>
	<input name="numero" label="NÃºmero">
		<rule name="number" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard"/>
		<rule name="required" />
	</input>
	<input name="cidade" label="Cidade">
		<rule name="discard"/>
		<rule name="required" />
	</input>
</form>
