=== bcordeirodev/acerbrag/Optimuz/config/dtd/validation.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT form (custom-rules*,input+)>
<!ATTLIST form
    method (get|post) #REQUIRED
    lang CDATA #IMPLIED
  >
<!ELEMENT custom-rules (rule)+>
<!ELEMENT rule EMPTY>
<!ATTLIST rule
    name (required|alpha|text|number|bool|array|email|url|date|password|comparePasswords|compareRequireds|compareDates|length|match|cnpj|cpf|upload|discard) #REQUIRED
    regex CDATA #IMPLIED
    errorMessage CDATA #IMPLIED
    accept CDATA #IMPLIED
    allowSequences (true|false) #IMPLIED
    sequencesMaxLength CDATA #IMPLIED
    min CDATA #IMPLIED
    max CDATA #IMPLIED
    fixed CDATA #IMPLIED
    types CDATA #IMPLIED
    size CDATA #IMPLIED
    items CDATA #IMPLIED
    second CDATA #IMPLIED
    requiredValue CDATA #IMPLIED
    differentValue CDATA #IMPLIED
    required (true|false) #IMPLIED
    strict (true|false) #IMPLIED
  >
<!ELEMENT input (rule)+>
<!ATTLIST input
    name CDATA #REQUIRED
    label CDATA #IMPLIED
	hasHTML (true|false) #IMPLIED
    isUrlEncoded (true|false) #IMPLIED
  >

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pesquisa/Nova.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="coordenada" regex="/-?\d+(\.\d+),-?\d+(\.\d+)/" errorMessage="Este campo requer valores de coordenadas" />
		<rule name="long" regex="/^-?\d+(\.\d+)?$/" errorMessage="A longitude não foi informada corretamente" />
		<rule name="lat" regex="/^-?\d+(\.\d+)?$/" errorMessage="A latitude não foi informada corretamente" />
	</custom-rules>
	<input name="titulo" label="Título">
		<rule name="discard" />
	</input>
	<input name="data-inicio" label="Data de início">
		<rule name="date" />
		<rule name="compareDates" second="data-fim" />
	</input>
	<input name="data-fim" label="Data de término">
		<rule name="date" />
	</input>
	<input name="descricao" label="Descrição da Pesquisa">
		<rule name="discard" />
	</input>
	<input name="quantidade-pontos" label="Quantidade de pontos">
		<rule name="required" />
	</input>
	<input name="tipo-pesquisa" label="Tipo de pesquisa">
		<rule name="required" />
	</input>
	<input name="pesquisa-anonima" label="Pesquisa anonima">
		<rule name="required" />
	</input>

	<input name="sexo" label="Sexo">
		<rule name="required" />
	</input>
	<input name="idade-minima" label="Idade Mínima">
		<rule name="required" />
	</input>
	<input name="idade-maxima" label="Idade Máxima">
		<rule name="required" />
	</input>

	<input name="text-question" label="">
		<rule name="discard" />
		<rule name="array" />
	</input>
	<input name="type-response" label="">
		<rule name="discard" />
		<rule name="array" />
	</input>
	<input name="category" label="">
		<rule name="discard" />
		<rule name="array" />
	</input>
	<input name="options" label="">
		<rule name="discard" />
		<rule name="array" />
	</input>
	<input name="required" label="">
		<rule name="discard" />
		<rule name="array" />
	</input>
	<input name="exception" label="">
		<rule name="discard" />
	</input>
	<input name="trigger" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Usuario/Listar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="get" lang="">
	<input name="start" label="Start">
		<rule name="number" />
	</input>
	<input name="length" label="Length">
		<rule name="number" />
	</input>
	<input name="draw" label="Draw">
		<rule name="number" />
	</input>
	<input name="search" label="Search">
		<rule name="text" />
	</input>
	<input name="time" label="Time">
		<rule name="number" />
	</input>
	<input name="limit" label="Limit">
		<rule name="number" />
	</input>
	<input name="show" label="Show">
		<rule name="discard" />
	</input>
	<input name="exportar" label="Exportar">
		<rule name="number" />
	</input>
	<input name="campo" label="Campo do filtro">
		<rule name="array" />
	</input>
	<input name="condicao" label="Condição do filtro">
		<rule name="array" />
	</input>
	<input name="valor" label="Valor do filtro">
		<rule name="array" />
	</input>
	<input name="operador" label="Operador do filtro">
		<rule name="array" />
	</input>
	<input name="tipo" label="Tipo">
		<rule name="match" requiredValue="excel,csv,pdf" />
	</input>
	<input name="removidos" label="Removidos">
		<rule name="number" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Pessoa/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4,5}-\d{4}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
	</custom-rules>

	<input name="id">
		<rule name="required" />
		<rule name="number" />
	</input>	
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>

	<input name="email" label="E-mail">
		<rule name="email" />
	</input>
	<input name="telefone" label="Tel. residencial">
		<rule name="phone" />
	</input>
	<input name="celular" label="Celular">
		<rule name="phone" />
	</input>
			
	<input name="cep" label="CEP">
		<rule name="cep" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard"/>
	</input>

	<input name="numero" label="NÃºmero">
		<rule name="number" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard"/>
	</input>
	<input name="cidade" label="Cidade">
		<rule name="discard"/>
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Instituicao/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4}-\d{4,5}/" errorMessage="O formato do telefone deve ser 00 00000-0000" />

		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
		<rule name="long" regex="/^-?\d+(\.\d+)?$/" errorMessage="A longitude não foi informada corretamente" />
		<rule name="lat" regex="/^-?\d+(\.\d+)?$/" errorMessage="A latitude não foi informada corretamente" />
	</custom-rules>

	<input name="nome-fantasia" label="Nome fantasia">
		<rule name="required" />
	</input>
	<input name="razao-social" label="Razão social">
		<rule name="required" />
	</input>
	<input name="responsavel-legal" label="Responsável legal">
		<rule name="discard" />
	</input>
	<input name="responsavel-comunicacao" label="Responsavel comunicação">
		<rule name="discard" />
	</input>
	<input name="cnpj" label="CNPJ">
		<rule name="required" />
	</input>
	<input name="site" label="Site">
		<rule name="discard" />
	</input>
	<input name="email" label="CNPJ">
		<rule name="required" />
	</input>
	<input name="telefone" label="Site">
		<rule name="discard" />
	</input>

	<input name="sobre-nos" label="Sobre nós">
		<rule name="discard" />
	</input>
	<input name="missao" label="Missão">
		<rule name="discard" />
	</input>
	<input name="visao" label="Visão">
		<rule name="discard" />
	</input>
	<input name="valores" label="Valores">
		<rule name="discard" />
	</input>

	<input name="cep" label="CEP">
		<rule name="cep" />
		<rule name="required" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard" />
		<rule name="required" />
	</input>
	<input name="longitude" label="Longitude">
		<rule name="long" />
		<rule name="required" />
	</input>
	<input name="latitude" label="Latitude">
		<rule name="lat" />
		<rule name="required" />
	</input>
	<input name="numero" label="Numero">
		<rule name="number" />
		<rule name="discard" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard" />
		<rule name="required" />
	</input>
	<input name="cidade" label="Cidade">
		<rule name="number" />
		<rule name="required" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Agenda/Salvar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="cep" regex="/\d{5}-\d{3}/" errorMessage="O formato do CEP deve ser 00000-000" />
	</custom-rules>

	<input name="titulo" label="Nome fantasia">
		<rule name="required" />
	</input>
	<input name="data" label="Data">
		<rule name="required" />
	</input>
	<input name="hora" label="Data">
		<rule name="required" />
	</input>
	<input name="titulo" label="Nome fantasia">
		<rule name="required" />
	</input>
	<input name="descricao" label="Razão social">
		<rule name="required" />
	</input>
	<input name="igrejas" label="Lugar a apresentar">
		<rule name="array" />
	</input>

	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>

	<input name="cep" label="CEP">
		<rule name="cep" />
		<rule name="required" />
	</input>
	<input name="logradouro" label="Logradouro">
		<rule name="discard"/>
		<rule name="required" />
	</input>
	<input name="numero" label="Número">
		<rule name="number" />
	</input>
	<input name="complemento" label="Complemento">
		<rule name="discard" />
	</input>
	<input name="uf" label="UF">
		<rule name="number" />
		<rule name="required" />
	</input>
	<input name="bairro" label="Bairro">
		<rule name="discard"/>
		<rule name="required" />
	</input>
	<input name="cidade" label="Cidade">
		<rule name="discard"/>
		<rule name="required" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Usuario/Editar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4,5}-\d{4}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cep-rule" regex="/\d{5}-\d{3}/" errorMessage="O formato do cep deve ser 00000-000" />
	</custom-rules>
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>
	<input name="telefone" label="Telefone">
		<rule name="phone" />
	</input>
	<input name="nivel" label="Nível">
		<rule name="number" />
	</input>
	<input name="permissoes" label="Permissões">
		<rule name="array" errorMessage="Selecione uma ou mais permissões" />
		<rule name="discard" />
	</input>
	<input name="id" label="ID do usuário">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="filial" label="Filiais">
		<rule name="array" errorMessage="Selecione uma ou mais filiais" />
		<rule name="discard" />
	</input>

</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Video/Atualizar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<input name="id" label="Id do podcast">
		<rule name="required" />
		<rule name="number" />
	</input>
	<input name="titulo" label="Título do vídeo">
		<rule name="required" />
	</input>
	<input name="url" label="Url do vídeo">
		<rule name="required" />
	</input>
	<input name="descricao" label="Descrição do vídeo">
		<rule name="required" />
	</input>
	<input name="igrejas" label="Lugar a apresentar">
		<rule name="array" />
	</input>
	<input name="status" label="">
		<rule name="required" />
	</input>
	<input name="arquivo" label="">
		<rule name="discard" />
	</input>
	<input name="nome-arquivo" label="">
		<rule name="discard" />
	</input>
</form>

=== bcordeirodev/acerbrag/Optimuz/apps/default/validation/Usuario/Novo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "http://optimuz.interativadesenvolvimento.com.br/dtd/validation.dtd">
<form method="post" lang="">
	<custom-rules>
		<rule name="phone" regex="/\d{2} \d{4,5}-\d{4}/" errorMessage="O formato do telefone deve ser 00 0000-0000" />
		<rule name="cep-rule" regex="/\d{5}-\d{3}/" errorMessage="O formato do cep deve ser 00000-000" />
		<rule name="cpf-rule" regex="/\d{3}.\d{3}.\d{3}-\d{2}/" errorMessage="O formato do telefone deve ser 000.000.000-00" />
	</custom-rules>
	<input name="nome" label="Nome">
		<rule name="required" />
	</input>
	<input name="email" label="E-mail">
		<rule name="required" />
		<rule name="email" />
	</input>
	<input name="telefone" label="Telefone">
		<rule name="phone" />
		<rule name="required"/>
	</input>
	<input name="cpf" label="CPF">
		<rule name="cpf-rule"/>
		<rule name="discard"/>
	</input>
	<input name="nivel" label="Nível">
		<rule name="number" />
	</input>
	<input name="perfil-usuario" label="Tipo de usuário">
		<rule name="number" />
	</input>

	<input name="senha" label="Senha">
		<rule name="required" />
		<rule name="password" accept="letters,numbers,symbols" allowSequences="false" sequencesMaxLength="4" />
		<rule name="length" min="8" />
	</input>
	<input name="confirma-senha" label="Confirmar senha">
		<rule name="required" />
		<rule name="comparePasswords" second="senha" />
	</input>
	<input name="permissoes" label="Permissões">
		<rule name="array" errorMessage="Selecione uma ou mais permissões" />
	</input>
	<input name="filial" label="Filiais">
		<rule name="array" errorMessage="Selecione uma ou mais filiais" />
		<rule name="discard" />
	</input>
</form>
